### ISSUE TITLE
npm install warning when installing bunyan

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#101]
When running npm install in the node-client-api dir on Windows, I get the following error. I do not see it when installing the node client api in my own project. That is, it seems like a dev thing, not an api-consumer issue.
```
cd f:/git/node-client-api
npm install
…
npm http 200 https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz
 
> dtrace-provider@0.3.1 install F:\git\node-client-api\node_modules\bunyan\node_modules\dtrace-provider
> scripts/install.js
 
'scripts' is not recognized as an internal or external command, operable program or batch file.
npm WARN optional dep failed, continuing dtrace-provider@0.3.1
multipart-stream@1.0.0 node_modules\multipart-stream
…
```

npm v1.4.9
node v0.10.28

**Comment by ehennum** [comment]
I can reproduce the issue.  The issue seems to resie with bunyan or npm.  

In that case, we could submit a pull request to fix the issue, but we would need to delve into bunyan to figure out what's going on.  Given that it's merely a spurious warning during install (and presuming that, if the fix is simple, the Bunyan maintainers will address it), we should focus on other issues.
