### ISSUE TITLE
Include queryBuilder with databaseClient instance

### ISSUE THREAD

**Issue by withjam** [marklogic/node-client-api#125]
I think it might help module creation if the queryBuilder was also attached to the instance of databaseClient created.  If a module accepts an instance of our databaseClient it could ensure that it also has the corresponding version of the queryBuilder that comes with it.  It's possible that a module's dependencies won't be at the most recent version of the node-client-api, in which case they'd get a newer databaseClient but only have access to the queryBuilder from their own marklogic version.  So instead of this:
    var marklogic = require('marklogic');
    var queryBuilder = marklogic.queryBuilder; // this comes from the dependency of the module
    function myModule(dbClient) {  // dbClient is passed by the app, and may be a different version

It would all be derived from the client

```
function myModule(dbClient) {
    var queryBuilder = dbClient.dbQuery; 
```

Does it make sense to anyone else to attach it like this?  Or was there a different reason for isolating it to the marklogic module itself?

**Comment by ehennum** [comment]
That would prevent the mismatch where the client is passed in but wouldn't prevent the converse mismatch where the query builder is passed in.

Instead of mixing, a better approach would be for a library either to own responsibility for the marklogic dependency or to receive the dependency from the caller but not both.  In other words, the call could pass the marklogic namespace object exported by the require.  The factory functions for creating a client, creating a query builder, and so on will always be compatible because they are in the same exported object.

The rationale for the organization is to put functions with a dependency on the connection in the client object.  The builders don't have that dependency.

**Comment by georgeajit** [comment]
Closing the issue to keep API stabilized.
