### ISSUE TITLE
Invalid constraint error not caught

### ISSUE THREAD

**Issue by dmcassel** [marklogic/node-client-api#167]
With either a Promise or Callback approach, an error with `qb.bind()` doesn't not get passed to the error handling function. I have to rely on a separate try/catch to handle the error. I believe that's a bug. 

In the examples below, "parts" is not a valid constraint. 

Promise approach: error should be handled by `.catch()`: 

    try {
      db.documents.query(
        qb.where(
          qb.bind({ parts: 'foo' })
        )
      ).result()
      .then(
        function(documents) {
          console.log('Found ' + documents.length + ' documents');
        })
      .catch(
        function(error) {
          console.log('oops: ' + JSON.stringify(error, null, 2));
        })
      .finally(
        function(param) {
          console.log('ss-facet finally');
        });
    } catch (e) {
      console.log('caught exception: ' + e);
    }

Callback approach. Error should be handled by the error-handling function (second parameter to `.result()`):

    try {
      db.documents.query(
        qb.where(
          qb.bind({ parts: 'foo' })
        )
      ).result(
        function(documents) {
          console.log('Found ' + documents.length + ' documents');
        },
        function(error) {
          console.log('oops: ' + JSON.stringify(error, null, 2));
        }
      );
    } catch (e) {
      console.log('caught exception: ' + e);
    }

In both cases, I get the "caught exception: " message.

**Comment by csreddy** [comment]
I think you are using ```bind()``` in wrong way, the documentation shows that you need to pass it a parameter to  ```q.parsedBindings()``` as shown below (taken from docs) 
```javascript
db.documents.query( qb.where(
  qb.parsedFrom('marklogic AND rep GT 50',
    qb.parseBindings(
      qb.word('aboutMe', qb.bindDefault()),
      qb.range('reputation', qb.datatype('int'), qb.bind('rep'))
  ))
)).result(function (documents) {
  console.log(JSON.stringify(documents[0].content, null, 2));
}, function(error) {
  console.log(JSON.stringify(error, null, 2));
});```

**Comment by ehennum** [comment]
In Promises, an error in your success callback is not caught in the error callback for the same response but, instead, in a subsequent error callback in the Promise chain.  That's why it's recommended to always append a catch() callback (not a try/catch) at the end of the Promises chain.  

That's standard behaviour for Promises.  Perhaps the JSDoc could be improved on that point.

**Comment by kcoleman-marklogic** [comment]
I added some guidance on this to the documentation of Promises in 8.0-2 (not in the JSDoc, though), but it sounds like it would help to explicitly say a try/catch isn't gonna do it. "Do this, not this" instead of just "Do this." :)

http://docs.marklogic.com/guide/node-dev/intro#id_94923

**Comment by ehennum** [comment]
I misread the original problem discussion.  The Node.js API follows a consistent policy of failing early on programming errors by throwing an exception.  For instance, in the case above, the bind() call will never succeed because of the programming error.

The feedback to the programmer is not to wrap the call in  a try/catch but, instead, to fix the call.

Note also that this issue is really orthogonal to Promises.  When the bind call fails, control hasn't even passed to the where() clause and definitely not to the result() call, which chooses to process the output with Promises instead of Streams.
