### ISSUE TITLE
Clarification: node 0.12 supported?

### ISSUE THREAD

**Issue by nikos** [marklogic/node-client-api#170]
With a current system (here: Mac OS X with brew) making use of node 0.12 when trying to install marklogic npm the following warning (in red) is put into the users console and might lead to confusion:

```
npm WARN engine marklogic@1.0.2: wanted: {"node":">=0.10.26 <0.11"} (current: {"node":"0.12.4","npm":"2.10.1"})
```

Is node 0.12 fully supported, should it be documented or reflected in the dependency descriptor accordingly?

**Comment by ehennum** [comment]
For the develop branch (which should be pushed to the master branch as a new release in the near future), we ran our unit tests and regressions on both Node.js 0.12 and io.js a few weeks back without finding any issues.

However, given that Node.js 0.12 and io.js are both stablizing and will continue to be unstable as they merge, our recommendation is to continue to use Node.js 0.10 for enterprise production work.  For exploratory use, however, it looks like you should be able to use the develop branch with either Node.js 0.12 or io.js 

The develop branch is particularly recommended for io.js because some of the develop dependencies work better with the ES6 features than the master dependencies.  In particular, I was able to yield on the Promise returned by the result() function, which makes for a more straightforward coding style.
