### ISSUE TITLE
Document server affinity and load balancing considerations

### ISSUE THREAD

**Issue by jmakeig** [marklogic/node-client-api#177]
Multi-statement transactions and eval/invoke with server fields require E-node affinity. We should document this.

**Comment by kcoleman-marklogic** [comment]
The MST part of this issue was addressed in a previous release. As for eval/invoke:

After a brief discussion with Erik, I'm pushing this one, too, with the same caveat that I will pull it into 3.0-4 if everyone runs out of other things to do and has time to think about this. Reason is that sorting out even just the eval/invoke context across all the layers (REST,XDBC, Node.js, Java) isn't going to be a quickie.

**Comment by kcoleman-marklogic** [comment]
Since there is still no data, there will be no documentation in 9.0-1. This seems likely to languish eternally since no one on the dev team owns it, and it is not even clear which one of them _should_ own it. 

For lack of a better idea, I will assign to Nalini to find an owner on her team.

**Comment by kcoleman-marklogic** [comment]
There's no writeup for eval/invoke, as per the discussion of this task in bugtrack. However, I wrote up more detailed coverage for the transaction context, based on Sam's wiki writeup, as part of Java Client 4.0.2 and ML 9.0-2. You can find it here:

http://docs.marklogic.com/guide/node-dev/transactions#id_39877

If more than this is required, then you'll have to let me know what it is. Otherwise, I would imagine you can close this.

**Comment by gvaidees** [comment]
@jmakeig Can this be closed?
