### ISSUE TITLE
403 Response when using qb.extract with qb.withOptions({categories:"none"})

### ISSUE THREAD

**Issue by brightgarden** [marklogic/node-client-api#185]
#### Per documentation at this [link](https://docs.marklogic.com/guide/search-dev/query-options#id_pgfId-1099193): 

> The Node.js Client API supports extract-document-data through the queryBuilder.extract method. By default, DatabaseClient.documents.query is a multi-document read, so it returns the extracted content as individual documents. **You can request a search result summary instead, including the extracted content by using queryBuilder.withOptions({categories: 'none'}).** For details, see Extracting a Portion of Each Matching Document in the Node.js Application Developer's Guide.

Note that the [Extracting a Portion of Each Matching Document](https://docs.marklogic.com/guide/node-dev/search#id_17648) does *not* imply that you can combine the qb.extract with qb.withOptions({categories: 'none'}), so maybe the documentation snippet above is just incorrect, or perhaps I am misunderstanding what it means.

#### When you do this, the REST-API throws a 403 response:

    {
	    "errorResponse": {
		    "statusCode": 403,
		    "status": "Forbidden",
		    "messageCode": "SEC-PRIV",
		    "message": "You do not have permission to this method and URL."
	    }
    }

##### Here is the Request body:

    {
    	"search": {
    		"options": {
    			"transform-results": {
    				"apply": "snippet"
    			},
    			"return-results": true,
    			"extract-document-data": {
    				"extract-path": ["/code", "/name", "/region", "/geo"],
    				"selected": "include"
    			},
    			"search-option": ["unfiltered"]
    		},
    		"qtext": "Australia"
    	}
    }

##### Headers:

    Content-Type: application/json
    Accept: application/json
    X-Error-Accept: application/json

##### Request URL:

`http://127.0.0.1:8015/v1/search?format=json&start=1&pageLength=10&view=results`

##### Data: 

For this issue, I used the sample data in /node_modules/marklogic/examples/data and loaded it per ../examples/before-load.js.

##### Troubleshooting: 

I have tried this out using [Postman](https://www.getpostman.com/), and at least discovered the following:

- changing "return-results" in the request body to "false" returns successfully, but of course, has no results.
- removing the entire "extract-document-data" property from the request body returns successfully, but of course, there's no extracted data.

My fallback is to omit the "qb.withOptions({ categories: "none" }) and interleave my results with the snippets, but it would be great if I didn't have to do this.

**Comment by ehennum** [comment]
Thanks for the detailed issue report.  Can you provide the Node.js code so I can try to reproduce the issue?

**Comment by brightgarden** [comment]
Here is the code snippet. Is this enough to go on?

	qb.where(
	  qb.parsedFrom("Australia")
	)
	.slice(1,10, 
	  qb.snippet(), 
	  qb.extract({
	    selected: "include",
	    paths: ["/code", "/name", "/region", "/geo"]
	  })
	)
	.withOptions({ categories: "none" })

**Comment by brightgarden** [comment]
Also, my MarkLogic server is at version 8.0-2.

**Comment by ehennum** [comment]
Thanks for the detail.  I'm not able to reproduce the issue on the next release (which will become 8.0-4).

A related bug in the Search API was fixed on 8.0-3.  (Bug 33349, which was not documented because it was believed to be a regression during 8.0-3 development, but that might not have been the case.)  I'd suggest upgrading to 8.0-3 to see if that fixes the problem.

One footnote:  the 1.0-3 Node.js API was developed and tested against 8.0-3 MarkLogic Server and so might have issues running against 8.0-2

Another footnote:  to execute a query on a word, you can use qb.term() and skip the parse step. (I understand, however, that the eventual goal might be to support parsed queries.)

**Comment by brightgarden** [comment]
Thanks. I will give it a try. At the moment, I am having some difficulty figuring out how to upgrade to 8.0-3. I will probably defer the attempt until next week. But if you know of a super quick guide (link) that will show me the way, I would really appreciate it.

The parse will be expected to take free form text a user types into a google-like search box, and we expect to support the DSL if the user happens to know it.

**Comment by ehennum** [comment]
Thanks for your willingness to give 8.0-3 a try.  Just so you know, the window for fixing bugs in 8.0-4 might close soon.  

If you're just testing, you might want to start with a clean install.  Otherwise, you would backup the current database and then follow the instructions in:

http://docs.marklogic.com/guide/installation/procedures#id_49025

Thanks also for clarifying that the goal is to support parsed queries.  Using qb.parsedFrom() in testing makes sense with that goal.

**Comment by brightgarden** [comment]
Thanks! I just upgraded and tested. Looks good!

**Comment by ehennum** [comment]
Thanks for the crisp investigation.
