### ISSUE TITLE
Verify and support Node 4.*

### ISSUE THREAD

**Issue by jmakeig** [marklogic/node-client-api#196]
https://nodejs.org/en/blog/release/v4.0.0/

**Comment by ehennum** [comment]
We'll need to determine when Node 4 is solid enough to be a fully supported engine.

Switching to Node 4 as a required engine will mean dropping some current library dependencies in favour of Node.js 4 built-in support and some resulting refactoring as well as refactoring to take advantage of E6 and ES6-friendly refinements to the interface.

Flipping it back to an RFE because of the interface aspects of the adoption.

**Comment by robcolburn** [comment]
@ehennum - Many project choose to support Node 4 in a phased fashion.

* Basic Compatibility: targeting a current stable branch, and only requiring a minor version bump.  This phase may include upgrading/enhancing dependencies to have basic Node 4 support. 
* Enhancement: taking advantage of a more robust API.

Is there opportunity to get to Basic Compatibility in the short-term?  Doing so could help applications that are otherwise prevented from upgrading to stable/supported Node.

**Comment by ehennum** [comment]
@robcolburn - we want to support performant and reliable enterprise production deployments. I'm guessing Node 4 will be shaking out side effects of the IO / Node merge for a while (but I would be happy to be wrong). 

I did run our basic tests on Node 4 a few weeks ago, and they all ran green. So, even if we're not ready to recommend Node 4 for production, experiments might work in the short term.

**Comment by robcolburn** [comment]
@ehennum,
Yes, I'm actually targeting an enterprise production deployment for my corp. ;)  We have a project that integrates ML in addition to other API's.  Personally, I don't work on the ML pieces of that project, but it seems our only issue upgrading is the engine warning during install.  If your tests are green, I'll ask my team-mates to run their tests as well. Thanks!

If we do run into minor/fixable compat issues, can I throw a PR your way? If so, should I target `master` branch?

**Comment by ehennum** [comment]
@robcolburn - It sounds like you're not running into any significant issues with Node 4, which is an interesting data point. Yes, please feel free to submit a PR.  Here's what we request:

https://github.com/marklogic/node-client-api/blob/master/CONTRIBUTING.md

The develop branch is pretty stable at this point because 8.0-4 is expected out in the near term (with forward looking caveats).

**Comment by ayuwono** [comment]
Just want to put some details, ran qa tests with 4.0.0 and it's green too

**Comment by csreddy** [comment]
adding another data point;  ran bugtrack node tests (total 294), all of them passed. Used v4.2.1.

**Comment by ehennum** [comment]
Stating the obvious, the engine has to change:

https://github.com/marklogic/node-client-api/blob/develop/package.json#L38

**Comment by alexmilowski** [comment]
The package.json file has been updated.

**Comment by ayuwono** [comment]
Please revert the change on master and make the change on develop, then we will push it to master
