### ISSUE TITLE
Patch Builder - replaceInsert adds object

### ISSUE THREAD

**Issue by tamaspiros** [marklogic/node-client-api#216]
Given a sample JSON structure:
```
{
"originalFilename": "../data/photos//07.JPG", 
"filename": "07.JPG", 
"binary": "/binary/07.JPG", 
"make": "Apple", 
"model": "iPhone 4", 
"created": 1310826505000, 
"location": {
"type": "Point", 
"coordinates": [
38.8895, 
-77.031833
], 
"city": "Washington", 
"country": "United States"
}
}
```

Calling the patch builder's `replaceInsert()` on this data structure with the following parameters causes some inconsistencies:

`pb.replaceInsert('/title', '/filename', 'after', { title: update.title })`

At the first execution a title property would be added after the `filename` property just as expected. However calling the same application code for the second time will add a new property under the already existing one:

```
{
"originalFilename": "../data/photos//07.JPG", 
"filename": "07.JPG", 
"title": {
"title": "test title"
}, 
"binary": "/binary/07.JPG", 
"make": "Apple", 
"model": "iPhone 4", 
"created": 1310826505000, 
"location": {
"type": "Point", 
"coordinates": [
38.8895, 
-77.031833
], 
"city": "Washington", 
"country": "United States"
}
}
```

According to the documentation (unless I misunderstand it) this should not happen as the 'content' states: "If select targets a property and content is an object, the operation replaces the entire target property. Otherwise, the operation replaces just the value" (https://docs.marklogic.com/guide/node-dev/partial-update#id_36747) So when the code gets called for the second time select should target a property and the content is an object.

**Comment by kcoleman-marklogic** [comment]
I would say that statement is a cut and paste error in the documentation.

The problem is that you cannot construct a combination of select, context, and content that does what you want in both the insert and the replace cases. In this instance, for the insert to work properly, you must express the content as an object ({title: initialValue}), but for the replace to work properly, you have express the content as a value. 

The replace part of replaceInsert did what you told it to: It replaced the value of the "title" property with the value you gave it ({title: update.title"). IMO, replaceInsert is just this side of useless unless you're working with arrays. 

You are bumping into this limitation:

"One implication of the anonymity of properties is that you cannot use a replace-insert operation to perform an operation like 'insert this property if it doesn't exist; otherwise, replace it.' Nor can you use separate insert and replace operations to achieve the same effect because the supported subset of XPath for JSON does not enable testing for the non-existence."

https://docs.marklogic.com/guide/rest-dev/documents#id_88350

**Comment by tamaspiros** [comment]
Hi Kim - thanks for your reply and sorry for the tardy response. I guess based on what you found in our documentation I need to programatically check for the existence of the property and update it if it exists, otherwise insert the object.

(This has been discussed here: https://github.com/marklogic/node-client-api/issues/61)

**Comment by kcoleman-marklogic** [comment]
Yes, unfortunately, I would say that is correct, Tamas.
