### ISSUE TITLE
db.documents.remove always returns removed: true

### ISSUE THREAD

**Issue by tamaspiros** [marklogic/node-client-api#228]
Probably a minor thing but the following code snippet would always return a `removed: true` property - even when a document does not exists:

```javascript
db.documents.remove('/user/tamas.json').result()
.then(function(response) {
  console.log(response)
});
```

```
{ uri: '/user/tamas.json',
  uris: [ '/user/tamas.json' ],
  removed: true }
```

Running the script twice (or even thrice) would still give me `removed: true`. Shouldn't this return a different message indicating that the document did not exist at the first place?

**Comment by ehennum** [comment]
The Node.js API follows the REST API in treating DELETE as idempotent.  

In fact, because the REST API always responds with a success status code if the document doesn't exist at the end of the request (regardless of whether it did exist at the start of the request), the Node.js API has no choice in the matter.

(You can find strong opinions in the REST community both for and against a strict interpretation of DELETE idempotency.)

**Comment by tamaspiros** [comment]
I see, thanks @ehennum. It's probably a very bad practice anyway for anyone to rely on a .delete() or .remove() method to determine the original existence of a document.
