### ISSUE TITLE
db.resources.post throws an error when no documents param is specified

### ISSUE THREAD

**Issue by jhoy** [marklogic/node-client-api#257]
When using db.resources.post with a REST API resource service extension, the documents parameter is supposed to be optional (confirmed with @ehennum ).  

However if the documents parameter is not specified, an error is thrown in resources-exec.js at line 232 when the code tries to perform a for loop on documents (which in this case would be "undefined").  The error it throws is a generic "Cannot read property 'length' of undefined", and the only way to figure out what's going on is with a debugger.

I think this part needs to be bypassed if documents isn't specified.

Thanks,

J.

**Comment by wooldridge** [comment]
@ayuwono To test, create a resource service extension with POST and PUT methods. Then call those methods with argument objects that don't include a documents property, e.g.:

db.resources.post({name: 'versionService'});
db.resources.put({name: 'versionService'});

**Comment by MayankBhatnagar89** [comment]
Hi Mike,

I created resource service extension named as "xqyServiceName" and tried caling methods : db.resources.put({name:xqyServiceName}) and db.resources.post({name:xqyServiceName})
But both are throwing out error : 
{
    "message": "wrapperService: response with invalid 500 status",
    "statusCode": 500,
    "body": {
        "errorResponse": {
            "statusCode": 500,
            "status": "Internal Server Error",
            "messageCode": "INTERNAL ERROR",
            "message": "XDMP-JSONCHAR: xdmp:unquote(\"{&quot;wroteDoc&quot;:{&#10;            &quot;param&quot;:&quot;...\") -- Unexpected character '}' in JSON at line 4 char 13 . See the MarkLogic server error log for further detail."
        }
    }
}

Please look into it.

**Comment by wooldridge** [comment]
@MayankBhatnagar89 I'm not sure what's going on with your test. Are you quoting the service name? For example:

db.resources.put({name:'xqyServiceName'})

Also, with you test, can you successfully call the service with the other properties in the param object? For example:

db.resources.put({
  name: 'xqyServiceName',
  params: {foo: 'bar'},
  documents: {key: 'value'}
})

Can you send me the code for the extension you are installing?

**Comment by wooldridge** [comment]
@MayankBhatnagar89 please provide a reproducible test case, thanks!

**Comment by MayankBhatnagar89** [comment]
Hi @wooldridge 

I am able to successfully call the service with other properties in the param object and I am not using quoting the service name. 
I am using wrapperService.xqy whose path is node-client-api/test-basic/data/wrapperService.xqy

Below is the sample code  : 
------------------------------------------------------------
var should = require('should');

var fs = require('fs');
var valcheck = require('core-util-is');

var testconfig = require('../etc/test-config-qa.js');

var marklogic = require('../');
var q = marklogic.queryBuilder;

var db = marklogic.createDatabaseClient(testconfig.restWriterConnection);
var restAdminDB = marklogic.createDatabaseClient(testconfig.restAdminConnection);

describe('when executing resource services', function(){
  describe('using XQuery', function() {
    var xqyServiceName = 'wrapperService';
    var xqyServicePath = './node-client-api/test-basic/data/wrapperService.xqy';
    before(function(done){
      this.timeout(10000);
      restAdminDB.config.resources.write(xqyServiceName, 'xquery', fs.createReadStream(xqyServicePath)).
      result(function(response){
        done();
      }, done);
    });

it('test code with arguments', function(done){
      db.resources.put({
        name:xqyServiceName, params: {foo: 'bar'},documents: {key: 'value'}
        }).
      result(function(response){
        console.log(response);
        done();
      },function(error){
      console.log(error);
      done();
      });
    });
 it('test code without arguments', function(done){
      db.resources.put({name: xqyServiceName}).
      result(function(response){
        console.log(responce);
        done();
      },function(error){
      console.log(error);
      done();
      });
    });
   });
});
------------------------------------------------------------


Output : 
------------------------------------------------------------
  when executing resource services
    using XQuery

{ wroteDoc: { param: 'UNDEFINED', inputDoc: { key: 'value' } } }
      â test code with arguments (865ms)

{ [Error: wrapperService: response with invalid 500 status]
  message: 'wrapperService: response with invalid 500 status',
  statusCode: 500,
  body:
   { errorResponse:
      { statusCode: 500,
        status: 'Internal Server Error',
        messageCode: 'INTERNAL ERROR',
        message: 'XDMP-JSONCHAR: xdmp:unquote("{&quot;wroteDoc&quot;:{&#10;            &quot;param&quot;:&quot;...") -- Unexpected character \'}\' in JSON at line 4 char 13 . See the MarkLogic server error log for further detail.' } } }
      â test code without arguments (109ms)

------------------------------------------------------------

Thanks,
Mayank

**Comment by wooldridge** [comment]
The issue is with the logic in wrapperService.xqy, line 56:
```
"inputDoc":',head((head($input)/xdmp:quote(.),'"UNDEFINED"')),
```
When no input documents are passed in for a PUT, "head($input)/xdmp:quote(.)" still evaluates to something that is non-empty, and that leads to invalid JSON being returned:
```
{"wroteDoc":{
  "param":"UNDEFINED",
  "inputDoc":
}}
```
instead of this:
```
{"wroteDoc":{
  "param":"UNDEFINED",
  "inputDoc":"UNDEFINED"
}}
```
I'm investigating how to address this.

**Comment by wooldridge** [comment]
Hi @MayankBhatnagar89 

@ehennum pointed out that the PUT method is always expected to provide a document payload. So we should only be testing this for POST.

However, the same issue is coming up with POST using analogous test code, i.e.:
```
db.resources.put({name: xqyServiceName})
```

**Comment by wooldridge** [comment]
More background on what is happening...

As the logic is currently written, when we execute a POST with no document payload on an installed resource extension, the Node.js API executes an 'empty' HTTP call. (When documents are included, it executes a 'multipart' HTTP call.)

When we execute a POST with no payload, the POST function of the installed resource extension, e.g.:
```
declare function wrapperService:post(
    $context as map:map,
    $params  as map:map,
    $input   as document-node()*
) as document-node()*
```
receives a (seemingly) empty $input value of the hexBinary type. However, an XQuery empty($input) call returns false. It is not recognized as empty like other types, which is why the current test code causes an error (invalid JSON is generated).

I've found workarounds for this (in wrapperService.xqy), for example converting the $input to a string and then checking the string length (is it 0?) or checking the type of $input, and then acting appropriately for the condition where the value is a hexBinary (signifying no input).  But adding this logic causes other tests that use the wrapperService.xqy file to fail (namely tests that send multiple documents). 

I see a couple ways to address this:

1. Rewrite the test to use a different XQY service file. Currently we have a test that's expecting a non-empty payload.
2. Rewrite the underlying code to result in $input not being hexBinary. There seems to be a problem in that the hexBinary type works differently than the other XQuery types here.

**Comment by ehennum** [comment]
Thanks for the additional detail.  This sounds like a bug on the REST API, which shouldn't return false when a resource service extension has no output.

**Comment by grechaw** [comment]
I don't completely understand this issue, but have seen hexBinary before.  You may have found an issue with its root cause in the HTTP server, not REST.

But go ahead and submit a REST bug if you can and we'll work to isolate the issue further.

**Comment by ehennum** [comment]
After sitting down with Mike, I can see that I completely misinterpretted this as a regression on the output.

The problem here is that wrapperService.xqy is not a good extension for testing this fix.

wrapperService.xqy is written to require input.

This fix is to support a client that's not providing input.

Thus, the test should use a different extension that doesn't require input.

**Comment by ayuwono** [comment]
Verified passed and added test nodejs-issue-257.js
