### ISSUE TITLE
Move kerberos dependencies to optionalDependencies in package.json

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#275]
Making kerberos and related modules optional is useful for developers who don't need Kerberos authentication (the majority don't) and don't have the environment to support it. More info:

https://docs.npmjs.com/files/package.json#optionaldependencies

The kerberos module includes native C++ code and is a more complicated dependency to get working, more info here:

https://www.npmjs.com/package/kerberos

@kcoleman-marklogic brought this issue to our attention.

@ayuwono adds:

There are several dependencies need to be installed on the machine, I can name:

Node-gyp
Python
Glibc-devel 64-bit (sudo yum install glibc-devel.x86_64)

And I think it has different dependencies on windows machine too

**Comment by kcoleman-marklogic** [comment]
This might end up being a useful reference to include in the README, as it does talk about the deps. Silly me, not to have looked there previously.

https://www.npmjs.com/package/kerberos

**Comment by kcoleman-marklogic** [comment]
I have officially given up on getting Node.js to npm install on Windows until Kerberos slinks off to the corner where it belongs. 

Heaven help the poor user who actually needs our API + Kerberos on Windows. I've wasted most of this week trying to get our install working on Windows, without success. I wound up in Windows SDK hell, and am now worse off than when I started. 

We won't have updated JSDoc for the API on pubs until this issue is addressed, which I realize is a minor matter compared to the potential user pain. I mention it only in case you go looking for the docs and wonder why they are not up to date.

**Comment by wooldridge** [comment]
@kcoleman-marklogic hoping the #277 merge addresses your install issues. @ehennum thanks for the help!

**Comment by kcoleman-marklogic** [comment]
Here is what I found:

`npm install` coughs up a bunch of errors because it still tries to install the optional deps by default. However, the install succeeds now since the failed dep is optional.

`npm install --no-optional` completes without error since it skips over the Kerberos stuff altogether.

If that's the desired usage, then we're good to go. I do think it is potentially alarming/confusing to see those errors, even though the install succeeds. It looks just like when it fails. :-/ It'd be nice if Kerberos was somehow opt-in instead of just skippable, but I'm not sure npm puts those tools in our hands.

**Comment by kcoleman-marklogic** [comment]
P.S. I also made another attempt to get the kerberos install working today, just because it bugs me to be defeated by an installer, but I was beaten again. I got node-gyp to install finally, but Kerberos still won't build.

I suspect a conflict between [the bundle of tools](https://github.com/felixrieseberg/windows-build-tools) node-gyp points Windows users to (which is how I finally got a successful node-gyp install), and what Kerberos wants. One seems based on VS 2015 and the other recommends only VS 2010. Unfortunately, I haven't found any chatter about the error I'm getting, so I'm going to slink back to my corner again. For now.

**Comment by ayuwono** [comment]
Verified that npm install --no-optional works fine and not installing kerberos

It seems that it's the only way to omit the kerberos installation. We should document this clearly.

**Comment by patrickmcelwee** [comment]
This issue has re-emerged, because --no-optional is overridden by npm shrinkwrap, which was [added to the project in May 2017](https://github.com/marklogic/node-client-api/commit/f694d5051e8a26d50e49351bc42da83ef7e5c130#diff-36018a6a9e1de1798516799b84841318). This means that if I run `npm install marklogic --no-optional`, I still get kerberos.

I can workaround this with adding `--no-shrinkwrap`, as in `npm install marklogic --no-optional --no-shrinkwrap`, but that means throwing away the locked-down dependencies. For a library that includes this one, it might mean throwing away shrinkwraps for other dependencies as well, if I want to run a single command to install everything.

**My suggestion is that you remove kerberos from the generated shrinkwrap.** This was suggested in this comment: https://github.com/npm/npm/issues/2679#issuecomment-150084700

Experimenting locally with a library that includes this library as a dependency, I found that removing [these lines](https://github.com/marklogic/node-client-api/blob/master/npm-shrinkwrap.json#L77-L82) from `npm-shrinkwrap.json` (and also from `package.json`, where they get included when this library is published) meant that:

1. `npm install --no-optional` did NOT include kerberos in my node_modules, and
2. `npm install` DID include kerberos, though presumably not necessarily the shrink-wrapped version.

(For context, I need this functionality in order to avoid a Python dependency when distributing a reusable Node middle tier.)

**Comment by wooldridge** [comment]
@patrickmcelwee, thanks for pointing this out and suggesting a fix. I will investigate editing the `npm-shrinkwrap.json`.

**Comment by wooldridge** [comment]
Confirming what @patrickmcelwee describes...

Run in current project (v2.1.1): `npm install --no-optional`

kerberos IS installed (when it shouldn't be)

Update project by removing kerberos settings ([lines 77-82](https://github.com/marklogic/node-client-api/blob/master/npm-shrinkwrap.json#L77-L82)) from npm-shrinkwrap.json

Run in updated project: `npm install --no-optional`

kerberos IS NOT installed (so the above update fixes the problem)

Run in updated project: `npm install`

kerberos IS installed (as it should be)
