### ISSUE TITLE
metadataValues null value is returned as an empty string instead of null

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#280]
Write this document, it has metadataValues of 'meta4' with null value:

```
    db.documents.write({
      uri: '/test/metadata/values/doc1.json',
      collections: ['metadataValuesColl'],
      contentType: 'application/json',
      quality: 250,
      properties: {
        prop1:'bar',
        prop2:1981
      },
      metadataValues: {
        meta1: 'super plastic',
        meta2: 45.89,
        meta3: true,
        meta4: null,
        meta5: undefined
      },
      content: {
        id: '0001',
        name:'bowl'
      }
    })
```

Read the document:
```
    db.documents.read({
      uris: ['/test/metadata/values/doc1.json'],
      categories:['content', 'metadataValues']
    })
```

Result in JSON.Stringify():
```
[
    {
        "uri": "/test/metadata/values/doc1.json",
        "category": "content",
        "format": "json",
        "contentType": "application/json",
        "contentLength": "28",
        "metadataValues": {
            "meta2": 45.89,
            "meta3": true,
            "meta1": "super plastic",
            "meta4": ""
        },
        "content": {
            "id": "0001",
            "name": "bowl"
        }
    }
]
```

Notice that 'meta4' value is an empty string instead of null. It should be null

If we pass this JSON object on JSON.stringify:
```
JSON.stringify({test1: null}, null, 2)
```

It will return:
{
  "test1": null
}

**Comment by ehennum** [comment]
Hi, @ayuwono -- for a null in document content or document properties content, it makes perfect sense that a null should always remain a null.

A null in document key-values metadata, however, can't remain a null because values are always a string.  (Apologies for not thinking of this case earlier.)

To put it another way, the values in a key-value map are all strings. As a convenience, the Node.js API can serialize non-string values to strings, but it cannot roundtrip such values because the original datatype cannot be known.

Our choices, then, seem to be either to emit an empty string for a null or to throw an error.

**Comment by ayuwono** [comment]
For the test, assertion will expect an empty string
