### ISSUE TITLE
update copyright notices for 2017

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#340]
When you do this, please don't forget the one that goes into the jsdoc. It is here:

https://github.com/marklogic/java-client-api/blob/develop/pom.xml#L65

**Comment by wooldridge** [comment]
@kcoleman-marklogic I'm not seeing the jsdoc file you're referring to in the node-client-api repo. I'm also not seeing a 2016 date in the doc files after I do a 'gulp doc'.

**Comment by wooldridge** [comment]
OK, we figured it out:

https://github.com/marklogic/node-client-api/blob/develop/gulpfile.js#L45

**Comment by wooldridge** [comment]
Fixed by the following, thanks @ayuwono:

https://github.com/marklogic/node-client-api/commit/b8c7828bcac093aca50a78b506f0189c19551fb7

https://github.com/marklogic/node-client-api/commit/2a1714993f1a9fa1389bf86435ee890941f05460

https://github.com/marklogic/node-client-api/commit/5ae34c410eaa243cc96e6aec26bf4b2affc8075b

https://github.com/marklogic/node-client-api/commit/1774374978aec462addb87a61c9ec43d9714a654
