### ISSUE TITLE
Node.js Client API unit test failures

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#383]
Build: 03/02

There are a couple of failures on Node API unit tests on Jenkins:
 
http://jenkins.marklogic.com/view/Node%20API/job/NodeAPIUnitTests_develop_xdmp-trunk/lastCompletedBuild/testReport/

```
 document content write a language-specified XML string."before all" hook
 Stack Trace
write single document: cannot process response with 400 status
undefined

 graph operations.should run a bound SPARQL update
 Stack Trace
expected {} to have property 'marklogic.com/r1'
AssertionError: expected {} to have property 'marklogic.com/r1'
    at Proxy.Assertion.fail (node_modules/should/lib/assertion.js:228:17)
    at Proxy.prop.(anonymous function) (node_modules/should/lib/assertion.js:69:14)
    at test-basic/graphs.js:246:28
    at tryCatcher (node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (node_modules/bluebird/js/main/async.js:15:14)
```

**Comment by wooldridge** [comment]
@ayuwono, the first "language-specified XML" issue references a test that was removed a few weeks ago: https://github.com/marklogic/node-client-api/commit/61861a627be8cc201f1e595523cd3e7562a8f0e8

Maybe this has something to do with the recent removal of lang support in the REST layer here:

https://bugtrack.marklogic.com/44500

But I don't understand when the now-removed Node.js test is still showing up. Thoughts?

**Comment by ayuwono** [comment]
@wooldridge, I have no idea why it's still showing up. I'm trying to grep under test-basic folder and the test description is not there

Maybe @jhoy might know it better. I checked the jenkins stdout and it's doing git checkout on develop

**Comment by wooldridge** [comment]
I explained the graphs test failure to @grechaw by email and I'm hoping he has some insight. The SPARQL Update query for that test is not inserting the expected triple. Here is the query:
```
CREATE GRAPH <marklogic.com/graph3> ; 
INSERT { GRAPH <marklogic.com/graph3> { ?s ?p "literal2" } } 
WHERE  { GRAPH <marklogic.com/graph2> {?s ?p ?o. filter (?p = ?b1) } }
``` 
with the following bindings:
```
{
  b1: 'marklogic.com/p1',
  b2: {value:'a value', type:'string'}
}
```
When I create the `marklogic.com/graph3` graph separately and then run the following in QConsole (same INSERT WHERE code but without the binding via URL params):
```
INSERT { GRAPH <marklogic.com/graph3> { ?s ?p "literal2" } } 
WHERE  { GRAPH <marklogic.com/graph2> {?s ?p ?o. filter (?p = <marklogic.com/p1>) } }
```
I get a triple insertion. If this happened in the test, the test would pass.

For reference, here is the offending test:

https://github.com/marklogic/node-client-api/blob/master/test-basic/graphs.js#L229

@ayuwono is pegging the regression date at 12-20-2016 (from bugtrack).

**Comment by grechaw** [comment]
responded to @wooldridge , I think the test may have been a false pass before 44052 was fixed.  Just a guess there ,but I did find that the binding is probably wrong.  Server side, b1 should be 
b1: sem:iri('marklogic.com/p1').  In node, I think that this structure is probably correct, but somehow it's not getting to the REST layer as an IRI.

**Comment by wooldridge** [comment]
@grechaw, thank you so much. I suspected binding was the issue so I can now focus on that and try to take care of this.

**Comment by grechaw** [comment]
Not a problem -- I do recall I had to include a new test to prove the false positive.

Do an insert with a WHERE that matches, check for insert.  do an insert with a WHERE that does not, and check that nothing is inserted.

**Comment by wooldridge** [comment]
Pasting extremely helpful info from @grechaw via email:

I think the issue you have is with the type of your binding.

the INSERT is only triggered if the WHERE clause is matched.  I just tried this -
```
xdmp:document-insert("/bah.xml",

<sem:triples xmlns:sem="http://marklogic.com/semantics">
<sem:triple>
<sem:subject>marklogic.com/r1</sem:subject>
<sem:predicate>marklogic.com/p1</sem:predicate>
<sem:object datatype="http://www.w3.org/2001/XMLSchema#string">literal1</sem:object>
</sem:triple>
</sem:triples>)
;
sem:sparql("select ?s  ?o where {?s ?b1 ?o} limit 10", map:entry("b1", "marklogic.com/p1"));
sem:sparql("select ?s  ?o where {?s ?b1 ?o} limit 10", map:entry("b1", sem:iri("marklogic.com/p1")))
```
only the second sparql matches the triple, because all subjects and predicates in RDF are iris.

passing the binding as an iri is the way to go -- it will be faster than, say, casting to a string in the filter (which would also work)

If this is coming from node, a bug could be in the binding, REST is tricky there.  A bug that I'd reported, and was
fixed around when your issue popped up, had to do with matching in graphs -- probably you were getting a false pass before.
 
Looks like without a third :{type} part binds as IRI, that's what you'll want to make sure is happening.

https://docs.marklogic.com/REST/POST/v1/graphs/sparql

"bind:{name}* A binding name and value. This format assumes that the type of the bind variable is an IRI. "

**Comment by wooldridge** [comment]
I believe I found the problem. In the underlying REST calls, the `using-graph-uri` and `using-named-graph-uri` params take URI values as described here:

https://docs.marklogic.com/REST/POST/v1/graphs/sparql

The Node.js Client API docs have the corresponding `usingDefaultGraphs` and `usingNamedGraphs` params taking booleans:

https://docs.marklogic.com/jsdoc/graphs.html#sparqlUpdate

To fix the test, I need to have those values passed in from the Node.js Client API as URIs.

But for this particular test to work, I also have to switch to using the `usingDefaultGraphs` setting rather than the `usingNamedGraphs`:

https://github.com/marklogic/node-client-api/blob/master/test-basic/graphs.js#L232

@grechaw is this consistent with the SPARQL Update query above? Do we want to include `using-graph-uri` (`usingDefaultGraphs` in Node.js) rather than `using-named-graph-uri` (usingNamedGraphs` in Node.js)?

There's also a question of whether the mapping of `using-graph-uri` to `usingDefaultGraphs` from REST to Node.js is correct with respect to naming. In the REST docs for `using-graph-uri`, defaults are not mentioned at all:

> The URI of the graph or graphs to address as part of a SPARQL Update operation. Use with SPARQL Update only.

**Comment by wooldridge** [comment]
The test also passes when I remove this part altogether from the query:
```
usingNamedGraphs: true,
```
which is here:

https://github.com/marklogic/node-client-api/blob/master/test-basic/graphs.js#L232

I need to discuss with @grechaw what is the appropriate setting for this situation.

**Comment by wooldridge** [comment]
Chatted with @grechaw and got a few things cleared up:

- The `using-graph-uri` param is specifies the WHERE graph in SPARQL Update
- But we don't need to use a separate graph specification in our test since we're specifying the graph explicitly in the query; the separate graph specification is superfluous
- For hints on testing these params, see the SPARQL Update tests in the following: xdmp/tests/junit

**Comment by wooldridge** [comment]
Fixing test by changing what `usingDefaultGraphs` and `usingNamedGraphs` accept (URIs not booleans). Keeping `usingNamedGraphs` and adding `usingDefaultGraphs` in test for coverage purposes.

**Comment by wooldridge** [comment]
@ayuwono, I fixed the SPARQL Update test that was failing. The "language-specified XML string" test shouldn't be relevant.

You will need to fix tests that use the `graphs.sparqlUpdate()` function with `usingDefaultGraphs` and `usingNamedGraphs`properties. Those properties now take one or more URI values rather than booleans. The properties correspond to the `using-graph-uri` and `using-named-graph-uri` URL parameters in the REST API:

https://docs.marklogic.com/REST/POST/v1/graphs/sparql

**Comment by wooldridge** [comment]
@ayuwono, regarding the API changes described above, I would expect the following test (and similar ones that set `usingDefaultGraphs` or `usingNamedGraphsproperties`) to fail:

https://github.com/marklogic/node-client-api/blob/develop/test-complete/nodejs-sparql-update.js#L330

If the test is still passing, I'd guess it is passing because it thinks graphs in the test are named `false` and `true`, which is misleading since those parameters now take graph names rather than boolean values. Should we update the parameter values used in those tests to graph names?

**Comment by ayuwono** [comment]
Thanks for the update @wooldridge, I will update the graph names

**Comment by ayuwono** [comment]
The original test failures are fixed
