### ISSUE TITLE
Update compatibility info on release page for server 9.0-1 release

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#402]
Two items for Node.js came out of today's meeting on versioning:

- Add caveat to release page that version 8 compatibility is to support upgrade scenario. 
- New Node.js Client API version for the 9.0-1 server release will be 2.0-1 (not 2.0.0).

I've made updates to the draft release page to address the above, @jmakeig please review:

https://github.com/marklogic/node-client-api/releases

**Comment by kcoleman-marklogic** [comment]
What does this mean and is it something I should worry about for the product release notes?

>Add caveat to release page that version 8 compatibility is to support upgrade scenario.

Is the version really going to be 2.0-1 rather than 2.0.1?

Also, please don't wait quite so late to choose the version number in the future. We have to bake it into the doc build, too. It's OK - we've slipped the doc deadline by a day for other reasons - but I'd prefer us not to make a habit of it.

**Comment by ehennum** [comment]
Mike, won't the version number be 2.0.1 (and not 2.0-1)?

**Comment by wooldridge** [comment]
Sorry, that was a mistype, no hyphen. The version number will be 2.0.1.

**Comment by wooldridge** [comment]
We ended up tagging the release as 2.0.2.

2.0.1 was put out, but it was lacking some of the final documentation updates that were on the develop branch. We prepared a new release candidate with the updates and unpublished 2.0.1 on npm. As it turns out, you can't republish on npm with the same version tag. Following semver best practices, we released the updated version as 2.0.2.

See: https://www.npmjs.com/package/marklogic
