### ISSUE TITLE
change in .slice() behaviour between 1.0.6 and 2.0.2

### ISSUE THREAD

**Issue by tpiros** [marklogic/node-client-api#408]
The following code works with the API v1.0.6:

```javascript
db.documents.query(
  qb.where(
    qb.parsedFrom('tamas')
  ).slice(1, 2, qb.extract({
      paths: ['//name',]
    })
  )
).result()
.then(response => console.info(response))
.catch(error => console.error(error));
```

However when upgrading to 2.0.2 a different resultset is returned unless the .slice is changed to be the following:

```javascript
.slice(0, 2, qb.extract({
      paths: ['//name',]
    })
```

This has the potential to break existing code. I haven't seen any announcements about this change and at this point I'm not sure if this is a bug or a purposeful change in the API.

**Comment by ehennum** [comment]
Hi, Tamas:  If I recall correctly, early versions of 1.x had a design bug of one-based numbering (carried over from XQuery).  Later versions of 1.x introduced an opt-in to switch to zero-based numbering consistent with JavaScript.  In 2.x, the default for the flag is flipped, so applications can opt-out of zero-based numbering for backward compatibility.  Eventually, however, the flag might be removed, so applications should modify their code to use zero-based numbering.

If that's not in the release notes, the bug is to add this information to the release notes.

**Comment by tpiros** [comment]
Thanks @ehennum - I was looking at the ML9 release notes and I couldn't find it (https://docs.marklogic.com/guide/relnotes/chap3#id_53771) not sure if I was looking at the right place though.

**Comment by ehennum** [comment]
Hi, @tpiros -- it's covered in the incompatibilities section:

https://docs.marklogic.com/guide/relnotes/chap4#id_78125

**Comment by kcoleman-marklogic** [comment]
BTW, though valuesBuilder.slice did not get the same treatment in 9.0-1 (2.0.2), it will also use a zero-based scheme in the next Node.js Client release.

**Comment by tpiros** [comment]
Thanks to both of you - my bad I didn't see this part of the docs.

**Comment by tpiros** [comment]
@kcoleman-marklogic do you want to track the valueBuilder change in this issue or can I go ahead and close it?

**Comment by kcoleman-marklogic** [comment]
You can close this. I just wanted to let you know the additional change is coming.

**Comment by wooldridge** [comment]
Catching up since I was out on Friday. The update for valuesBuilder.slice is handled here: https://github.com/marklogic/node-client-api/issues/400

As described in the above issue, the change in functionality (for vauesBuilder.slice) actually went in with 2.0.2 (9.0-1) and the documentation will be added with the next minor release.
