### ISSUE TITLE
Patch XML document doesn't work if uri does not end with 'xml'

### ISSUE THREAD

**Issue by lifan0127** [marklogic/node-client-api#502]
Take the example from the [Node Developer guide](https://docs.marklogic.com/guide/node-dev/partial-update#id_35443):

```js
// (1) Insert the base document into the database
db.documents.write({
  uri: '/patch/raw-patch2.xml',  // <-- change this to ".txt" to trigger an error
  contentType: 'application/xml',
  content: '<parent><child>data</child></parent>'
}).result().then(function(response) {
  // (2) Patch the document
  return db.documents.patch(
    response.documents[0].uri, 
    '<rapi:patch xmlns:rapi="http://marklogic.com/rest-api">' +
    '  <rapi:insert context="/parent" position="last-child">' +
    '    <new-child>INSERTED</new-child>' +
    '  </rapi:insert>' +
    '</rapi:patch>'
  ).result();
}).then(function(response) {
  // (3) Emit the resulting document
  return db.documents.read(response.uri).result();
}).then(function(documents) {
  console.log(documents[0].content);
}, function(error) { console.log(error); throw error; });
```
The above example works as expected. However, __if the uri is changed to something like `/patch/raw-patch2.txt`, it will fail:__

```bash
  message: 'patch document: cannot process response with 400 status (on /patch/raw-patch2.txt)',
  statusCode: 400,
  body:
   { errorResponse:
      { statusCode: 400,
        status: 'Bad Request',
        messageCode: 'XDMP-JSONDOC',
        message: 'XDMP-JSONDOC: xdmp:get-request-body("json") -- Document is not JSON' } } }
```

**Comment by ehennum** [comment]
Patch operates only on structured documents -- that is, on JSON or XML.  A text document doesn't have any substructure to select for modification.

When a JSON or XML document is saved as text, the structure of the document isn't visible. To the server, the document is a single text string.  

The extension determines the format of the persisted document when written through the REST API.  For the specific details, see:

http://docs.marklogic.com/guide/rest-dev/intro#id_22986

The default mapping of the txt extension in the mime type mapping table is to the Text format.

For those reasons, the patch operation would be expected to fail if the xml extension is changed to a txt extension using the default mime type mapping table.

Hoping that clarifies,

**Comment by lifan0127** [comment]
@ehennum Thanks for your prompt response. Perhaps `txt` is a bad choice here but I just wanted to provide a minimal reproducible example.

My real problem comes when I try to patch the XML envelopes from PDF and Word documents ingested using the Data Hub Framework. Those documents have `pdf` and `docx` as extensions in their URIs and would result in the same error.

**Comment by ehennum** [comment]
The situation is similar for the pdf and docx extensions. 

The default mapping for the pdf and docx extensions is to the Binary format.  Binary documents have no exposed structure that can be patched.  That is, to the server, a binary document is a long single sequence of bytes.

In other words, to be able to patch the document, the document must have been inserted using an extension with a mapping to the JSON or XML format in the server's mime type mapping table at the time when the document was inserted.

**Comment by lifan0127** [comment]
You're right. The original document could be binary and in arbitrary format. During ingestion, the Data Hub Framework create an XML envelope structure using the document filter function. My goal is to patch the XML envelope not the original document.

**Comment by ehennum** [comment]
The approach depends on whether the harmonized flow persists the XML envelope structure

*  within an XML document that's the output from the harmonized flow
*  as an XML properties fragment for a binary document that's the output from the harmonized flow  
*  as an XML sidecar document associated with a binary document that's the output from the harmonized flow

If the XML envelope is stored within XML output, the patch should work if the output from the harmonized flow is persisted with a URI that has an extension mapped to the XML format.

If the XML envelope is stored in a properties fragment, the patch operation must specify the document properties.  See the properties operation as part of the following example:

http://docs.marklogic.com/guide/node-dev/partial-update#id_45792

If the XML envelope is stored in a sidecar document, the patch request must specify the URI of the sidecar document instead of the URI for the binary document.
